### ISSUE TITLE
Developer Preview

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/project#32]
# Goal

Prepare the Developer release of Halkyon

- [ ] Improve testing coverage to include new contract defintion to bind capabilities
- [ ] Replace supervisord with "rsync" and commands passed as runtime label
- [ ] Add Quarkus runtime
- [ ] Create and publish Halkyon developer experience doc
- [ ] Release halkyon and hal as DevPreview
- [ ] Verify i it works for the runtimes
- [ ] Add the prometheus and/or grafana plugin
- [ ] Something to be done from marketing point of view 
- [ ] Design some katacoda scenario
- [ ] Release Dekorate GA supporting this Dev Preview

@nainaz  Do you see something else to do ? What should be the release/announce date ?

**Comment by metacosm** [comment]
This issue should be put under the halkyonio/operator repository.

**Comment by metacosm** [comment]
Also, Quarkus is already supported.

**Comment by nainaz** [comment]
We should add support for Vert.x, Node and Thorntail

**Comment by cmoulliard** [comment]
This issue should be put under the halkyonio/operator repository.
> 
How can we move an epic from one repo to another @metacosm ?

**Comment by metacosm** [comment]
> We should add support for Vert.x, Node and Thorntail

vert.x and Thorntail are already supported and should work. Node.js is supposed to be supported already but currently doesn't work, see halkyonio/operator#191.

**Comment by metacosm** [comment]
> How can we move an epic from one repo to another @metacosm ?

It's easy if the repos are part of the same organization. If they aren't (which is the case here), it's not possible… or if it is, I don't know how. Only option I know is to close this issue and re-create one in the proper organization/repo.

**Comment by nainaz** [comment]
I meant add it as part of Goal  list.

**Comment by metacosm** [comment]
> I meant add it as part of Goal list.

Gotcha. Do you agree about the rest of it, @nainaz, so that we can get moving on this? If yes, I will move the issue to halkyonio/operator and create associated issues for each entry.

**Comment by nainaz** [comment]
Move the issue anyway. As it belongs there. 
And I agree with other points.

**Comment by metacosm** [comment]
Moved to halkyonio/operator.
